### Блок Numpy

In [1]:
import numpy as np

In [3]:
a = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]])
a

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [7]:
a = a.transpose()

In [8]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [9]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

In [10]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [13]:
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])
a_centered_sp

8.0

In [15]:
total = a_centered_sp / 4 # 5 - число наюлюдений равное кол-ву строк 
total

2.0

### Блок Pandas

In [16]:
import pandas as pd

In [19]:
authors = pd.DataFrame({'author_id': [1, 2, 3], 'author_name': ['Тургенев', 'Чехов', 'Островский']})
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [18]:
books = pd.DataFrame({'author_id': [1, 1, 1, 2, 2, 3, 3], 'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], 'price': [450, 300, 350, 500, 450, 370, 290]})
books

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

In [22]:
authors_price = pd.merge(authors, books, on = 'author_id')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [23]:
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [32]:
authors_stat = pd.DataFrame(authors_price['author_name'].unique())
authors_stat

0
0    Тургенев
1       Чехов
2  Островский

In [33]:
authors_stat['min_price'] = authors_price['price'].min()
authors_stat

0  min_price
0    Тургенев        290
1       Чехов        290
2  Островский        290

In [34]:
authors_stat['max_price'] = authors_price['price'].max()
authors_stat

0  min_price  max_price
0    Тургенев        290        500
1       Чехов        290        500
2  Островский        290        500

In [35]:
authors_stat['mean_price'] = authors_price['price'].mean()
authors_stat

0  min_price  max_price  mean_price
0    Тургенев        290        500  387.142857
1       Чехов        290        500  387.142857
2  Островский        290        500  387.142857